services:
  mongodb:
    image: mongo:7.0
    container_name: tailorapp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tailorapp
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tailorapp-network

volumes:
  mongodb_data:
    driver: local

networks:
  tailorapp-network:
    driver: bridge